// <auto-generated />
namespace Ada.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class OrderDetailUpdate20171229 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OrderDetailUpdate20171229));
        
        string IMigrationMetadata.Id
        {
            get { return "201712290808249_OrderDetailUpdate20171229"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
