// <auto-generated />
namespace Ada.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MediaUpdate20171217 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MediaUpdate20171217));
        
        string IMigrationMetadata.Id
        {
            get { return "201712170559416_MediaUpdate20171217"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
