// <auto-generated />
namespace Ada.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class InvoiceUpdate20171220 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InvoiceUpdate20171220));
        
        string IMigrationMetadata.Id
        {
            get { return "201712200302007_InvoiceUpdate20171220"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
