// <auto-generated />
namespace Ada.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RoleUpdate20171215 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RoleUpdate20171215));
        
        string IMigrationMetadata.Id
        {
            get { return "201712150343026_RoleUpdate20171215"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
