// <auto-generated />
namespace Ada.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class WorkFlowUpdate20181024 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WorkFlowUpdate20181024));
        
        string IMigrationMetadata.Id
        {
            get { return "201810240943303_WorkFlowUpdate20181024"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
